### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by GuenterWeitzer** [davcastroruiz/tamir.ssh#1]
Downloading this with nuget package manager gives a warning that the assembly is compiled for x86 only.
Because of that I wanted to download and compile it myself but I realized some files are missing.
These are the missing files:
\jsch\UserAuth.cs
\jsch\UserAuthKeyboardInteractive.cs
\jsch\UserAuthNone.cs
\jsch\UserAuthPassword.cs
\jsch\UserAuthPublicKey.cs
\jsch\UserInfo.cs
\jsch\Util.cs

**Comment by davcastroruiz** [comment]
Thanks Vigew, I just uploaded missing files.
